---
title: WZV Waalwijk
timezone: UTC
collections:
  classes:
    title: Classes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@wzvwaalwijk.nl
address: Zwembad Olympia Drunenseweg 11 5143 NE, Waalwijk
phone_number: 0416-123456
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
instagram_url: https://www.instagram.com/wzv_waalwijk/
facebook_url: https://www.instagram.com/wzv_waalwijk/
